meta_product_name: "Sounds in Bordeaux"
meta_title: "Sounds in Bordeaux | Agenda des événements éléctro à Bordeaux"
meta_description: "Sounds in Bordeaux, ton agenda des ssoirées et festivals à Bordeaux."
meta_image: "social.jpg"
twitter_account: "@SoundsBordeaux"
