# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 93db176aab7803aa824ac37493b001101fa911cddb25663453bbbcea83455a7edae3adeb6b1954d24c9b66c72eb2650c99323bd3576197ce1dbd1d186531fcb3

test:
  secret_key_base: 92da5c638342abb90f768ba200605988183e60324061acb65a7a77593377ed182361db6a6410d36bb2013d874cf2bc09f7ae712ef5958b0f2ec8edf982ee0c65

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
